//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAppRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANCOMOVIMIENTO
    {
        public decimal IDMOVIMIENTOBANCARIO { get; set; }
        public Nullable<System.DateTime> FECHAMOVBANCARIO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public decimal IDENTIDADBANCARIA { get; set; }
        public decimal IDEGRESO { get; set; }
        public decimal IDINGRESO { get; set; }
        public decimal IDTIPOCUENTA { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
        public virtual EGRESO EGRESO { get; set; }
        public virtual ENTIDADBANCARIA ENTIDADBANCARIA { get; set; }
        public virtual TIPOMOVBANCO TIPOMOVBANCO { get; set; }
    }
}
