//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAppRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAOPERACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAJAOPERACION()
        {
            this.INGRESO = new HashSet<INGRESO>();
        }
    
        public decimal IDCAJAOPERACION { get; set; }
        public Nullable<System.DateTime> FECHAAPERTURA { get; set; }
        public Nullable<decimal> MONTOAPERTURA { get; set; }
        public decimal IDCAJAESTADO { get; set; }
        public decimal IDUSUARIO { get; set; }
    
        public virtual CAJAESTADO CAJAESTADO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INGRESO> INGRESO { get; set; }
    }
}
