//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAppRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEORDEN
    {
        public decimal IDDETALLEORDEN { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public decimal IDORDEN { get; set; }
        public decimal IDESTADO { get; set; }
    
        public virtual ESTADOORDEN ESTADOORDEN { get; set; }
        public virtual ORDEN ORDEN { get; set; }
    }
}
