//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAppRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADBANCARIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTIDADBANCARIA()
        {
            this.BANCOMOVIMIENTO = new HashSet<BANCOMOVIMIENTO>();
        }
    
        public decimal IDENTIDADBANCARIA { get; set; }
        public string DESCBANCO { get; set; }
        public decimal IDTIPOCUENTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANCOMOVIMIENTO> BANCOMOVIMIENTO { get; set; }
        public virtual TIPOCUENTA TIPOCUENTA { get; set; }
    }
}
