//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAppRepo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantEntities : DbContext
    {
        public RestaurantEntities()
            : base("name=RestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANCOMOVIMIENTO> BANCOMOVIMIENTO { get; set; }
        public virtual DbSet<BODEGAMOVIMIENTO> BODEGAMOVIMIENTO { get; set; }
        public virtual DbSet<CAJAESTADO> CAJAESTADO { get; set; }
        public virtual DbSet<CAJAOPERACION> CAJAOPERACION { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<COMPRA> COMPRA { get; set; }
        public virtual DbSet<DETALLEORDEN> DETALLEORDEN { get; set; }
        public virtual DbSet<DOCTPAGOTIPO> DOCTPAGOTIPO { get; set; }
        public virtual DbSet<DOCUMENTOPAGO> DOCUMENTOPAGO { get; set; }
        public virtual DbSet<EGRESO> EGRESO { get; set; }
        public virtual DbSet<EMPLEADOTURNO> EMPLEADOTURNO { get; set; }
        public virtual DbSet<ENTIDADBANCARIA> ENTIDADBANCARIA { get; set; }
        public virtual DbSet<ESTADOMESA> ESTADOMESA { get; set; }
        public virtual DbSet<ESTADOORDEN> ESTADOORDEN { get; set; }
        public virtual DbSet<ESTADOPRODUCTO> ESTADOPRODUCTO { get; set; }
        public virtual DbSet<ESTADORESERVA> ESTADORESERVA { get; set; }
        public virtual DbSet<FUNCIONALIDAD> FUNCIONALIDAD { get; set; }
        public virtual DbSet<INGRESO> INGRESO { get; set; }
        public virtual DbSet<INSUMO> INSUMO { get; set; }
        public virtual DbSet<INSUMOSTOCK> INSUMOSTOCK { get; set; }
        public virtual DbSet<MEDIOPAGO> MEDIOPAGO { get; set; }
        public virtual DbSet<MEDIOPAGOTX> MEDIOPAGOTX { get; set; }
        public virtual DbSet<MESA> MESA { get; set; }
        public virtual DbSet<ORDEN> ORDEN { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PEDIDOINSUMO> PEDIDOINSUMO { get; set; }
        public virtual DbSet<PERMISOS> PERMISOS { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PRODUCTOPREPARACION> PRODUCTOPREPARACION { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<RECETAPRODUCTO> RECETAPRODUCTO { get; set; }
        public virtual DbSet<RESERVA> RESERVA { get; set; }
        public virtual DbSet<RESTAURANT> RESTAURANT { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<TIPOCUENTA> TIPOCUENTA { get; set; }
        public virtual DbSet<TIPOMOVBANCO> TIPOMOVBANCO { get; set; }
        public virtual DbSet<TIPOMOVBODEGA> TIPOMOVBODEGA { get; set; }
        public virtual DbSet<TIPOPREPARACION> TIPOPREPARACION { get; set; }
        public virtual DbSet<TIPOPRODUCTO> TIPOPRODUCTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIOROL> USUARIOROL { get; set; }
    }
}
